@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package io.github.mrp_v2.coloredobsidianexpansion.util.cryingobsidian;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;